var GW = {};
GW.ic = {
shield:'<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="m9 12 2 2 4-4"/></svg>',
badge:'<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76z"/><path d="m9 12 2 2 4-4"/></svg>',
users:'<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>',
phone:'<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0 1 22 16.92z"/></svg>',
mail:'<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="20" height="16" x="2" y="4" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/></svg>',
clock:'<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>',
arrow:'<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>',
chat:'<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m3 21 1.9-5.7a8.5 8.5 0 1 1 3.8 3.8z"/></svg>',
send:'<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m22 2-7 20-4-9-9-4z"/><path d="M22 2 11 13"/></svg>',
x:'<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>'
};

GW.nav = function(){return '<nav class="nav" id="main-nav"><a href="#/" class="nav-logo"><span>GOLDEN WAVE</span><span>INFRATECH PVT. LTD.</span></a><div class="nav-links" id="nav-links"><a href="#/" data-link="/">HOME</a><a href="#/ncr-monarch" data-link="/ncr-monarch">PROJECTS</a><a href="javascript:void(0)" onclick="document.getElementById(\'location-section\')&&document.getElementById(\'location-section\').scrollIntoView({behavior:\'smooth\'})">LOCATION</a><a href="javascript:void(0)" onclick="document.getElementById(\'enquiry-section\')&&document.getElementById(\'enquiry-section\').scrollIntoView({behavior:\'smooth\'})">CONTACT</a></div><button class="nav-cta" onclick="document.getElementById(\'enquiry-section\')&&document.getElementById(\'enquiry-section\').scrollIntoView({behavior:\'smooth\'})" id="nav-enquire">ENQUIRE NOW</button><div class="hamburger" id="hamburger" onclick="document.getElementById(\'nav-links\').classList.toggle(\'open\')"><span></span><span></span><span></span></div></nav>';};

GW.footer = function(){return '<footer class="footer" id="footer"><div class="container"><div class="footer-grid"><div class="footer-brand"><h3>GOLDEN WAVE</h3><div class="sub">INFRATECH PVT. LTD.</div><p>RERA-registered channel partner for premium 2 &amp; 3 BHK homes in Greater Noida West. 500+ families. Trusted. Verified.</p><div class="footer-rera"><div>2 &amp; 3 BHK: RERA — UPRERAPRJ4790</div><div>2 BHK Zen: SBI Ventures Managed</div></div></div><div class="footer-links"><div class="footer-col"><h4>NAVIGATE</h4><a href="#/">Home</a><a href="#/ncr-monarch">2 &amp; 3 BHK</a><a href="#/future-estates">2 BHK Zen</a></div><div class="footer-col"><h4>LEGAL</h4><a href="#/disclaimer">Disclaimer</a><a href="#/privacy">Privacy Policy</a><a href="#/terms">Terms &amp; Conditions</a></div><div class="footer-col"><h4>CONTACT</h4><p>+91-7835057660</p><p style="font-size:11px;word-break:break-all">digitalgoldenwaveinfra@gmail.com</p><p>Sector 1, Greater Noida West, UP 201306</p><a href="https://wa.me/917835057660" target="_blank" class="wa-btn" style="margin-top:12px;padding:10px;font-size:10px">WHATSAPP US</a></div></div></div><div class="footer-disclaimer">This website is operated by Golden Wave Infratech Private Limited, an RERA-registered channel partner. This is not the official website of any developer. All content, images, floor plans, and pricing are indicative only and subject to change without notice. Prices exclude GST, stamp duty, registration, and other charges. RERA: UPRERAPRJ4790.</div><div class="footer-bottom"><span>&copy; 2026 Golden Wave Infratech Private Limited. All rights reserved.</span><div><a href="#/disclaimer">Disclaimer</a><a href="#/privacy">Privacy</a><a href="#/terms">Terms</a></div></div></div></footer>';};

GW.form = function(){return '<div class="form-card" id="enquiry-form-card"><div class="toggle-group"><button class="toggle-btn active" onclick="this.parentElement.querySelectorAll(\'.toggle-btn\').forEach(function(b){b.classList.remove(\'active\')});this.classList.add(\'active\')">2 &amp; 3 BHK</button><button class="toggle-btn" onclick="this.parentElement.querySelectorAll(\'.toggle-btn\').forEach(function(b){b.classList.remove(\'active\')});this.classList.add(\'active\')">2 BHK ZEN</button></div><input class="form-input" placeholder="Full Name *" id="form-name" required><input class="form-input" placeholder="+91 Mobile Number *" id="form-mobile" required><input class="form-input" placeholder="Email (optional)" id="form-email"><select class="form-input" id="form-interest"><option value="">I\'m looking for…</option><option>2 BHK from ₹92.28L</option><option>3 BHK from ₹1.14 Cr</option><option>Floor Plans &amp; Pricing</option><option>Book a Site Visit</option></select><button class="form-submit" id="form-submit-btn">GET CALLBACK &amp; BEST PRICE →</button><p class="form-note">By submitting, you consent to be contacted by Golden Wave Infratech Pvt. Ltd.</p></div>';};

GW.connect = function(){return '<div class="connect-grid"><div class="connect-card"><div class="emoji">🚇</div><div class="place">Aqua Line Metro</div><div class="time">10 min</div></div><div class="connect-card"><div class="emoji">🛣️</div><div class="place">Noida–GN Expressway</div><div class="time">5 min</div></div><div class="connect-card"><div class="emoji">🎓</div><div class="place">Schools &amp; Colleges</div><div class="time">2–5 min</div></div><div class="connect-card"><div class="emoji">🏥</div><div class="place">Fortis / Yatharth Hospital</div><div class="time">10 min</div></div><div class="connect-card"><div class="emoji">🛍️</div><div class="place">Gaur City Mall</div><div class="time">8 min</div></div><div class="connect-card"><div class="emoji">🏢</div><div class="place">IT Parks Noida Sec 62</div><div class="time">20 min</div></div></div>';};
